import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync, mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generatedFiles, matchingContent } from './generated-config.mjs';

const directory = fileURLToPath(new URL('../', import.meta.url));
test('committed validation manifest matches the authoritative generator', () => {
  assert.deepEqual(JSON.parse(readFileSync(`${directory}/tools/gdq-generated-files.json`, 'utf8')), generatedFiles(directory));
});
test('manifest covers every Terraform-owned generated GDQ path', () => {
  const source = readFileSync(`${directory}/infrastructure/modules/general/main.tf`, 'utf8');
  const paths = [...source.matchAll(/^\s*file\s*=\s*"([^"]+)"/gm)].map(match => match[1]).sort();
  assert.deepEqual(Object.keys(generatedFiles(directory)).sort(), paths);
});
test('all generated file resources use the protected-only branch selector', () => {
  const source = readFileSync(`${directory}/infrastructure/modules/general/main.tf`, 'utf8');
  const blocks = [...source.matchAll(/resource "github_repository_file" "[^"]+" \{([\s\S]*?)(?=\nresource |$)/g)];
  assert.equal(blocks.length, Object.keys(generatedFiles(directory)).length);
  for (const block of blocks) assert.match(block[1], /branch\s*=\s*local.generated_config_branch/);
  assert.match(source, /generated_config_branch = var.infrastructure_review \? github_branch.generated_config\[0\].branch : null/);
});
test('manifest preserves protected policy and template substitutions', () => {
  const files = generatedFiles(directory);
  assert.match(files['.github/workflows/autogenerated-deploy.yml'], /infrastructure_review: true/);
  assert.doesNotMatch(files['.github/workflows/autogenerated-deploy.yml'], /GDQ_REVIEW_INPUTS/);
  assert.match(files['.github/workflows/autogenerated-automerge.yml'], /github.repository != 'mahn-ke\/gdqreminder-by-vincent'/);
  const renovate = JSON.parse(files['renovate.json']);
  assert.equal(renovate.automerge, false);
  assert.equal(renovate.dependencyDashboard, true);
  assert.deepEqual(renovate.vulnerabilityAlerts.labels, ['automerge', 'security']);
  assert.ok(matchingContent('renovate.json', JSON.stringify(renovate, null, 2), files['renovate.json']));
  assert.ok(!matchingContent('renovate.json', '{}', files['renovate.json']));
  assert.throws(() => generatedFiles(directory, 'repos'));
});
test('manifest matches Terraform heredoc and jsonencode semantics', { skip: process.env.TEST_TERRAFORM !== 'true' }, () => {
  const temporary = mkdtempSync(join(tmpdir(), 'generated-hcl-'));
  try {
    const source = readFileSync(`${directory}/infrastructure/modules/general/main.tf`, 'utf8');
    const header = source.match(/default\s*=\s*<<EOT\n([\s\S]*?)\nEOT/)[1];
    writeFileSync(`${temporary}/main.tf`, `locals {\n  header = <<EOT\n${header}\nEOT\n}\n`);
    const template = `${directory}/infrastructure/modules/general/src/.github/workflows/deploy.yml`;
    const output = execFileSync('terraform', [`-chdir=${temporary}`, 'console'], {
      input: `base64encode("\${local.header}\\n\${replace(file("${template}"), "# GDQ_REVIEW_INPUTS", "    with:\\n      infrastructure_review: true")}")\n`, encoding: 'utf8' }).trim();
    assert.equal(Buffer.from(JSON.parse(output), 'base64').toString(), generatedFiles(directory)['.github/workflows/autogenerated-deploy.yml']);
    const json = generatedFiles(directory)['renovate.json'];
    const encoded = execFileSync('terraform', [`-chdir=${temporary}`, 'console'], {
      input: `base64encode(jsonencode(jsondecode(${JSON.stringify(json)})))\n`, encoding: 'utf8' }).trim();
    assert.equal(Buffer.from(JSON.parse(encoded), 'base64').toString(), json);
  } finally { rmSync(temporary, { recursive: true, force: true }); }
});