import { readFileSync, writeFileSync, realpathSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const protectedRepository = 'gdqreminder-by-vincent';
export const generatedBranch = 'terraform/generated-config';

export function generatedFileResources(repositoryDirectory) {
  const source = readFileSync(join(repositoryDirectory, 'infrastructure/modules/general/main.tf'), 'utf8');
  return [...source.matchAll(/resource "github_repository_file" "([^"]+)" \{([\s\S]*?)(?=\nresource |$)/g)].map(match => {
    const path = match[2].match(/^\s*file\s*=\s*"([^"]+)"/m)?.[1];
    if (!path) throw new Error('Missing generated resource path');
    return { address: `module.general["${protectedRepository}"].github_repository_file.${match[1]}${match[1] === 'workflow_infrastructure_review' ? '[0]' : ''}`, path };
  });
}

export function generatedFiles(repositoryDirectory, repository = protectedRepository) {
  if (repository !== protectedRepository) throw new Error('Protected generator supports GDQ only');
  const moduleDirectory = join(repositoryDirectory, 'infrastructure/modules/general');
  const source = readFileSync(join(moduleDirectory, 'main.tf'), 'utf8');
  const header = source.match(/default\s*=\s*<<EOT\n([\s\S]*?)\nEOT/)?.[1];
  if (!header) throw new Error('Missing generator header');
  const read = path => readFileSync(join(moduleDirectory, path), 'utf8');
  const files = {};
  for (const name of ['automerge', 'deploy', 'plan-comment', 'infrastructure-review', 'backup', 'restore', 'terraform-lock-refresh']) {
    let content = read(`src/.github/workflows/${name}.yml`);
    if (name === 'deploy') content = content.replace('# GDQ_REVIEW_INPUTS', '    with:\n      infrastructure_review: true');
    files[`.github/workflows/autogenerated-${name}.yml`] = `${header}\n\n${content}`;
  }
  for (const root of ['infrastructure', 'service']) {
    files[`${root}/autogenerated-main.tf`] = `${header}\n\n${read(`${root}/main.tf`).replaceAll('$REPOSITORY', repository)}`;
    files[`${root}/.gitignore`] = `${header}\n\n${read(`${root}/.gitignore`)}`;
  }
  const renovate = JSON.parse(read('src/renovate.json5'));
  files['renovate.json'] = canonical({ ...renovate, dependencyDashboard: true, automerge: false,
    vulnerabilityAlerts: { enabled: true, labels: ['automerge', 'security'] } });
  return files;
}

export function canonical(value) {
  return JSON.stringify(value, (_, entry) => entry && typeof entry === 'object' && !Array.isArray(entry)
    ? Object.fromEntries(Object.entries(entry).sort(([first], [second]) => first.localeCompare(second))) : entry);
}

export function matchingContent(path, actual, expected) {
  if (path === 'renovate.json') {
    try { return canonical(JSON.parse(actual)) === canonical(JSON.parse(expected)); } catch { return false; }
  }
  return actual === expected;
}

if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(resolve(process.argv[1]))).href) {
  const directory = fileURLToPath(new URL('../', import.meta.url));
  const expected = `${JSON.stringify(generatedFiles(directory), null, 2)}\n`;
  const path = join(directory, 'tools/gdq-generated-files.json');
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== expected) throw new Error('Generated manifest differs from templates');
  } else writeFileSync(path, expected);
}