import assert from 'node:assert/strict';
import test from 'node:test';
import { adoptEntry, migrationEntries, prepareBranch, publishPR } from './generated-config-delivery.mjs';
import { generatedFiles } from './generated-config.mjs';
import { fileURLToPath } from 'node:url';

test('state adoption targets only GDQ file resources, preserving counted addresses', () => {
  const resource = { module: 'module.general["gdqreminder-by-vincent"]', type: 'github_repository_file', name: 'workflow_infrastructure_review',
    instances: [{ index_key: 0, attributes: { repository: 'gdqreminder-by-vincent', file: 'review.yml', branch: 'main' } }] };
  assert.deepEqual(migrationEntries({ resources: [resource, { ...resource, module: 'module.general["repos"]' }] }, { 'review.yml': '' }),
    [{ address: 'module.general["gdqreminder-by-vincent"].github_repository_file.workflow_infrastructure_review[0]', path: 'review.yml', migrate: true }]);
  assert.throws(() => migrationEntries({ resources: [resource] }, {}));
});
test('failed import restores only the original file association and stops adoption', () => {
  const calls = [];
  assert.throws(() => adoptEntry({ address: 'test.address', path: 'renovate.json' }, args => {
    calls.push(args);
    if (args.at(-1).endsWith(':terraform/generated-config')) throw new Error('Import failed');
  }), /original main association restored/);
  assert.equal(calls.length, 3);
  assert.equal(calls.at(-1).at(-1), 'gdqreminder-by-vincent:renovate.json:main');
  assert.ok(!calls.some(args => args.includes('push') || args.includes('apply')));
});
test('branch preparation recreates a deleted branch without modifying main', () => {
  const writes = [];
  const result = prepareBranch((endpoint, method, body) => {
    if (method) { writes.push({ endpoint, method, body }); return {}; }
    if (endpoint.endsWith('/heads/main')) return { object: { sha: 'a'.repeat(40) } };
    throw Object.assign(new Error('Not found'), { status: 404 });
  });
  assert.equal(result, 'created');
  assert.equal(writes[0].body.ref, 'refs/heads/terraform/generated-config');
  assert.equal(writes.length, 1);
});
test('publisher skips no diff and refuses unrelated edits', () => {
  const directory = fileURLToPath(new URL('../', import.meta.url));
  assert.equal(publishPR(() => ({ behind_by: 0, files: [] }), () => [], directory, 'a'.repeat(40)), 'no-change');
  assert.throws(() => publishPR(() => ({ behind_by: 0, files: [{ filename: 'app/main.js' }] }), () => [], directory, 'a'.repeat(40)), /Unrelated/);
});
test('branch preparation refuses unrelated edits before Terraform can overwrite them', () => {
  const writes = [];
  assert.throws(() => prepareBranch((endpoint, method) => {
    if (method) writes.push(endpoint);
    if (endpoint.includes('/compare/')) return { behind_by: 1, ahead_by: 1, files: [{ filename: 'app/index.js' }] };
    return { object: { sha: 'a'.repeat(40) } };
  }, { 'renovate.json': '{}' }), /Unrelated edits/);
  assert.deepEqual(writes, []);
});
test('publisher reuses a single PR only for exact trusted generated bytes', () => {
  const directory = fileURLToPath(new URL('../', import.meta.url));
  const manifest = generatedFiles(directory);
  const writes = [];
  const api = (endpoint, method, body) => {
    if (method) { writes.push({ endpoint, method, body }); return {}; }
    if (endpoint.includes('/compare/')) return { behind_by: 0, files: [{ filename: 'renovate.json', status: 'modified' }] };
    return { content: Buffer.from(manifest['renovate.json']).toString('base64') };
  };
  assert.equal(publishPR(api, () => [{ number: 1 }], directory, 'a'.repeat(40)), 'updated');
  assert.equal(writes.length, 1);
  assert.ok(writes[0].endpoint.endsWith('/pulls/1'));
});